server:
  port: 5050 # Port for the Admin service

spring:
  application:
    name: stock-service # Service name that will register to Eureka

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # URL of your Eureka server
    register-with-eureka: true
    fetch-registry: true # Enables fetching of other registered services
  
