server:
  port: 8086 # Port where the API Gateway will run

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://CUSTOMERSERVICE # Load balanced using Eureka
          predicates:
            - Path=/api/customers/**  # Route requests starting with /api/customers/ to customer-service
#        - id: stock-service
#          uri: lb://STOCK-SERVICE # Load balanced routing to stock service
#          predicates:
#            - Path=/api/stocks/**  # Route requests starting with /api/stocks/ to stock-service
      discovery:
        locator:
          enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Eureka Server URL
      register-with-eureka: true
      fetch-registry: true
      
      
      

