server:
  port: 8086 # Port where the API Gateway will run

#spring:
#  application:
#    name: api-gateway
#
#  cloud:
#    gateway:
#      routes:
#        - id: customer-service
#          uri: lb://CUSTOMERSERVICE # Load balanced using Eureka
#          predicates:
#            - Path=/api/customers/**  # Route requests starting with /api/customers/ to customer-service
#            
#        - id: stock-service
#          uri: lb://STOCKSERVICE # Load balanced routing to stock service
#          predicates:
#            - Path=/api/stocks/**  # Route requests starting with /api/stocks/ to stock-service
#            
#        - id: admin-service
#          uri: lb://ADMINSERVICE # Load balanced routing to stock service
#          predicates:
#            - Path=/api/admin/**  # Route requests starting with /api/stocks/ to stock-service
#            
#        - id: auth-service
#          uri: lb://AUTHSERVICE
#          predicates:
#            - Path=/api/auth/**
#            
#      discovery:
#        locator:
#          enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Eureka Server URL
      register-with-eureka: true
      fetch-registry: true
      
      
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://CUSTOMERSERVICE # Load balanced using Eureka
          predicates:
            - Path=/api/customers/**  # Route requests starting with /api/customers/ to customer-service
            
        - id: stock-service
          uri: lb://STOCKSERVICE # Load balanced routing to stock service
          predicates:
            - Path=/api/stocks/**  # Route requests starting with /api/stocks/ to stock-service
            
        - id: admin-service
          uri: lb://ADMINSERVICE # Load balanced routing to stock service
          predicates:
            - Path=/api/admin/**  # Route requests starting with /api/stocks/ to stock-service
            
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
      discovery:
        locator:
          enabled: true
      globalcors:
        add-to-simple-url-handler-mapping: true

        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
            allowedHeaders:
              - "Origin"
              - "Content-Type"
              - "Accept"
              - "Authorization"
              - "User-Key"
              - "Request-Tracker"
              - "Session-Tracker"
              - "X-XSRF-TOKEN"
              - "X-IBM-CLIENT-ID"
              - "Message-ID"
              - "X-IBM-CLIENT-SECRET"
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_FIRST
      
      
      
      
      

