server:
  port: 8761 # Default port for Eureka server

eureka:
  client:
    register-with-eureka: false # The server itself won't register with another Eureka server
    fetch-registry: false # It doesn't need to fetch registry from other instances

spring:
  application:
    name: eureka-server
